### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by HelloThere1911** [ParrotSec/changelog#4]
Your newest iso brings me the "_" and a black screen when I try and install it with the standard installer.  Your previous iso's didn't have this issue with my laptop.

Specs:  
Intel Celeron Processor N3060 (overclocked from 2.24ghz to 2.45ghz)
Intel HD 400 (integrated GPU)
eMMC 32GB Drive
2GB DDR3 Memory (low voltage)

**Comment by PalinuroSec** [comment]
enter the serial console and check the logs
