### ISSUE TITLE
Dual boot on win 10 with parrot os

### ISSUE THREAD

**Issue by noelxii12** [ParrotSec/changelog#5]
Hi,

I used my asus laptop with win10. Dual boot it with the latest parrot Os and everything was smooth in installing untill when i am at OS, it seems to missed out my wifi int. I reinstall the Os and i noticed that it skips the network interface stage and will go on to other steps. Boot into Os and still i got no wifi int connection. Any troubleshooting steps for this to bring back wlan as i tried terminal to up it but it gives me an error of no int.

**Comment by PalinuroSec** [comment]
what does it have to do with our release changelog?

anyway post this question in our community portal at community.parrotsec.org
